name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Check test image accessibility
        run: |
          curl -I https://raw.githubusercontent.com/romangricuk/image-previewer/master/test/data/gopher_50x50.jpg


      - name: Run lint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make integration-test

      - name: Build
        run: make build
