name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Run golangci-lint
        run: |
          golangci-lint run --config=.golangci.yml ./...

      - name: Run tests
        run: |
          go test -race -count 100 ./...

      - name: Build
        run: |
          go build -o image-previewer ./cmd/image-previewer
